name: Containerbau und Veröffentlichung

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - name: Repositorium ziehen
      uses: actions/checkout@v2

    - name: Baue Containerabbild
      run: docker build -t h-nvim:${{ github.run_number }} .

    - name: Beim Dockerdrehkreuz anmelden
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Veröffentlichung auf Dockerdrehkreuz
      run: docker push h-nvim:${{ github.run_number }}
