name: Containerbau und Veröffentlichung

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - name: Repositorium ziehen
      uses: actions/checkout@v2

    - name: Nix-Installation
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Baue Containerabbild
      run: docker load < $(nix build .#dockerImage)
      #run: docker build -t hafflationist/h-nvim:${{ github.run_number }} -f Containerfile .

    - name: Beim Dockerdrehkreuz anmelden
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Veröffentlichung auf Dockerdrehkreuz
      run: docker push hafflationist/h-nvim:latest
